-- Formatting Dates and Times
-- DATE_FORMAT(NOW(), '%M %D %Y') - %Y means year as a numeric value of 4-digits, %M as month in a string value, %D as date in a num of 2 digit
-- TIME_FORMAT(NOW(), '%H:%i %p') - Returns current time: 12:58 PM - H is hour limit from 00 to 23, i is min limit from 00 to 59,
--                                                                   p means AM or PM
