-- Creating Procedures Using MySQLWorkbench
-- On the left side panel right click on stored procedures --> create procedures --> type whatever needed --> click apply --> again apply
-- So it creates the SP 